# Try to find OpenGLES3. Once done this will define:
#     OPENGLES3_FOUND
#     OPENGLES3_INCLUDE_DIRS
#     OPENGLES3_LIBRARIES
#     OPENGLES3_DEFINITIONS

find_package(PkgConfig)

pkg_check_modules(PC_OPENGLES3 glesv3)

if (PC_OPENGLES3_FOUND)
    set(OPENGLES3_DEFINITIONS ${PC_OPENGLES3_CFLAGS_OTHER})
endif ()

find_path(OPENGLES3_INCLUDE_DIRS NAMES GLES3/gl3.h
    HINTS ${PC_OPENGLES3_INCLUDEDIR} ${PC_OPENGLES3_INCLUDE_DIRS}
)

if (UNIX AND NOT ANDROID)
    # On Linux GLESv3 and GLESv2 implemented in same shared library
    set(OPENGLES3_NAMES ${OPENGLES3_NAMES} GLESv2)
else()
    set(OPENGLES3_NAMES ${OPENGLES3_NAMES} GLESv3)
endif()

find_library(OPENGLES3_LIBRARIES NAMES ${OPENGLES3_NAMES}
    HINTS ${PC_OPENGLES3_LIBDIR} ${PC_OPENGLES3_LIBRARY_DIRS}
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(OpenGLES3 DEFAULT_MSG OPENGLES3_INCLUDE_DIRS OPENGLES3_LIBRARIES)

set(OPENGLES3_FOUND "${OpenGLES3_FOUND}")

if(OPENGLES3_FOUND AND NOT TARGET OpenGLES3::OpenGLES3)
    add_library(OpenGLES3::OpenGLES3 UNKNOWN IMPORTED)
    set_target_properties(OpenGLES3::OpenGLES3 PROPERTIES
        IMPORTED_LOCATION "${OPENGLES3_LIBRARIES}"
        INTERFACE_INCLUDE_DIRECTORIES "${OPENGLES3_INCLUDE_DIRS}"
    )
endif()

mark_as_advanced(OPENGLES3_INCLUDE_DIRS OPENGLES3_LIBRARIES)
